### ISSUE TITLE
Vagrant only works with selected versions of VirtualBox

### ISSUE THREAD

**Issue by jeremiah** [Pelagicore/pelux-manifests#64]
When trying to use the Vagrant based build version of PELUX I failed to get vagrant to run with Docker so I used VirtualBox instead. When running;

$ vagrant up 

I get; 

"The provider 'virtualbox' that was requested to back the machine
'default' is reporting that it isn't usable on this system. The
reason is shown below:

Vagrant has detected that you have a version of VirtualBox installed
that is not supported. Please install one of the supported versions
listed below to use Vagrant:

4.0, 4.1, 4.2, 4.3"

I'm using VirtualBox version 5.1.26r117224 on Debian buster/sid. Do I have to downgrade my VirtualBox to use Vagrant?

**Comment by breakreturn** [comment]
I think it might be the combination of your vagrant version and vbox version.

@tobsan Perhaps we should state in the README.md and relevant SWF docs what versions we've actually used to verify things.

**Comment by jeremiah** [comment]
Lemme get my vagrant version, I think it is kinda old.

**Comment by tobsan** [comment]
In the CI system setup we're building with Docker actually, so I can't really say we test this with VBox on a regular basis. Perhaps we should just remove the vbox support? It is equally easy to install Docker as VirtualBox, and since Docker doesn't do full virtualization, it would even be preferred from a performance point of view.

How about removing Vbox support?

**Comment by jeremiah** [comment]
@tobsan That works for me, if no one else needs vbox let's move to the Docker-only solution.

**Comment by DunderRoffe** [comment]
I'm all for removing vbox.
Maybe we should have tests for running the docker image for Windows and or Mac? Or state that it is only tested on linux.
